version: "3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=prem
      - FILE__PASS=/transmission_password
    volumes:
      - data-config:/config
      - /mnt/HC_Volume_37156271/from-hf-to-torrent/data:/downloads
      - /mnt/HC_Volume_37156271/from-hf-to-torrent/torrents:/torrents
      - /mnt/HC_Volume_37156271/from-hf-to-torrent/.client_password:/transmission_password
      - data-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  data-config:
  data-watch: